# Generated by Django 4.0 on 2024-02-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_img',
            field=models.ImageField(upload_to='proj_images/'),
        ),
    ]
