# Generated by Django 4.0 on 2024-02-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_project_proj_img_projectimage_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='proj_img',
            field=models.ManyToManyField(blank=True, to='cms.ProjectImage'),
        ),
    ]
