# Generated by Django 4.0 on 2024-02-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_project_proj_name_alter_project_proj_img'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='language',
            table='language',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
