# Generated by Django 4.0 on 2024-03-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_remove_projectimage_project_project_proj_img'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='information',
            table='personal_information',
        ),
        migrations.AlterModelTable(
            name='projectimage',
            table='project_images',
        ),
    ]
