# Generated by Django 4.0 on 2024-02-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_language_table_alter_project_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proj_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.project')),
            ],
            options={
                'db_table': 'project_image',
            },
        ),
    ]
