# Generated by Django 4.0 on 2024-02-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_project_table_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='proj_img',
        ),
        migrations.AddField(
            model_name='project',
            name='proj_img',
            field=models.ManyToManyField(to='cms.ProjectImage'),
        ),
    ]
