# Generated by Django 4.0 on 2024-02-14 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_projectimage_project_remove_project_proj_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='proj_img',
        ),
        migrations.AddField(
            model_name='project',
            name='proj_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='proj_images/'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='projectimage',
            table=None,
        ),
    ]
