# Generated by Django 4.0 on 2024-02-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_remove_project_proj_img_project_proj_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='image',
            new_name='proj_img',
        ),
    ]
