# Generated by Django 4.0 on 2024-02-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_rename_image_projectimage_proj_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_type',
            field=models.CharField(choices=[('Application', 'Application'), ('Graphic Art', 'Graphic Art'), ('Logo', 'Logo')], default='Application', max_length=20),
        ),
    ]
