# Generated by Django 4.0 on 2024-02-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_project_proj_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelTable(
            name='language',
            table='languages',
        ),
    ]
