# Generated by Django 4.0 on 2024-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_information_alter_language_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='middle_initial',
            field=models.CharField(default='T.', max_length=10),
        ),
    ]
