# Generated by Django 4.0 on 2024-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_information_middle_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='middle_initial',
            field=models.CharField(max_length=10),
        ),
    ]
