# Generated by Django 4.0 on 2024-02-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_information_middle_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='email_add',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='github_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
