# Generated by Django 4.0 on 2024-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_information_email_add_information_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_lang',
            field=models.ManyToManyField(blank=True, null=True, to='cms.Language'),
        ),
    ]
